# Generated by Django 2.2.7 on 2019-12-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='creation_time',
            field=models.DateTimeField(default='1970-01-01 00:00+0000'),
            preserve_default=False,
        ),
    ]
