# Generated by Django 2.2.7 on 2019-12-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20191202_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
