# Generated by Django 2.2.7 on 2019-12-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20191202_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default='1970-01-01 00:00+0000'),
            preserve_default=False,
        ),
    ]
