# Generated by Django 2.2.7 on 2019-12-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_post_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Tytuł posta', max_length=31),
            preserve_default=False,
        ),
    ]
