# Generated by Django 2.2.7 on 2019-12-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='users',
            field=models.ManyToManyField(to='common.User'),
        ),
        migrations.DeleteModel(
            name='UserSection',
        ),
    ]
