# Generated by Django 2.2.10 on 2020-03-02 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20191204_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
