# Generated by Django 3.0 on 2020-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20191204_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='icon',
            field=models.CharField(default='laptop', max_length=63),
        ),
    ]
