# Generated by Django 2.2.9 on 2020-02-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_post_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='implied_tags',
            field=models.ManyToManyField(related_name='implied_tags', to='common.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='common.Tag'),
        ),
        migrations.CreateModel(
            name='TagImplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='common.Tag')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='common.Tag')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Section')),
            ],
        ),
    ]
