# Generated by Django 2.2.9 on 2020-03-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20200227_1642'),
        ('common', '0007_section_icon'),
    ]

    operations = [
    ]
