# Generated by Django 2.2.10 on 2020-03-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_user_last_activity_time'),
        ('common', '0011_merge_20200302_1353'),
    ]

    operations = [
    ]
