# Generated by Django 3.0 on 2020-03-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_vote'),
        ('common', '0011_merge_20200302_1353'),
    ]

    operations = [
    ]
