# Generated by Django 2.2.9 on 2020-03-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_user_description'),
        ('common', '0011_merge_20200302_1353'),
    ]

    operations = [
    ]
