# Generated by Django 2.2.9 on 2020-03-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20200311_2153'),
        ('common', '0012_merge_20200314_1143'),
    ]

    operations = [
    ]
