# Generated by Django 2.2.9 on 2020-03-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_merge_20200315_2033'),
        ('common', '0012_merge_20200315_1502'),
    ]

    operations = [
    ]
