# Generated by Django 2.2.9 on 2020-03-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20200330_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagimplication',
            name='section',
        ),
    ]
