# Generated by Django 2.2.10 on 2020-04-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_commentvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.SmallIntegerField(null=True),
        ),
    ]
