# Generated by Django 2.2.10 on 2020-04-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_remove_tagimplication_section'),
        ('common', '0017_comment_depth'),
    ]

    operations = [
    ]
