# Generated by Django 3.0 on 2020-04-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20200408_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', height_field='80', upload_to='profile_images/', width_field='80'),
        ),
    ]
