# Generated by Django 3.0 on 2020-04-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20200408_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', height_field='image_height', upload_to='profile_images/', width_field='image_width'),
        ),
    ]
