# Generated by Django 3.0 on 2020-04-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20200408_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
    ]
