# Generated by Django 3.0 on 2020-04-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20200408_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_images/'),
        ),
    ]
