# Generated by Django 3.0 on 2020-04-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20200411_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_field',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='width_field',
            field=models.IntegerField(null=True),
        ),
    ]
