# Generated by Django 3.0 on 2020-04-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_auto_20200411_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', height_field='height_field', upload_to='', width_field='width_field'),
        ),
    ]
