# Generated by Django 3.0 on 2020-04-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_auto_20200420_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_mini',
            field=models.ImageField(default='default_mini.jpg', upload_to=''),
        ),
    ]
