# Generated by Django 3.0 on 2020-05-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_user_image_mini'),
        ('common', '0019_auto_20200407_1150'),
    ]

    operations = [
    ]
