# Generated by Django 2.2.9 on 2020-05-19 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_merge_20200512_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='punctation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_punctation_changeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_update_punctation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TagPunctation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctation', models.FloatField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User')),
            ],
        ),
        migrations.CreateModel(
            name='PostVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_counter', models.SmallIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User')),
            ],
        ),
    ]
